#
# Copyright (c) 2025 The SPEAR Development Team. Licensed under the MIT License <http://opensource.org/licenses/MIT>.
# Copyright (c) 2022 Intel. Licensed under the MIT License <http://opensource.org/licenses/MIT>.
#

import argparse
import glob
import json
import numpy as np
import os
import shutil
import spear


parser = argparse.ArgumentParser()
parser.add_argument("--external-project-dir")
args = parser.parse_args()


if __name__ == "__main__":

    external_project_dir = os.path.realpath(args.external_project_dir)
    uprojects = glob.glob(os.path.realpath(os.path.join(external_project_dir, "*.uproject")))
    assert len(uprojects) == 1
    uproject = uprojects[0]
    uproject_dir = os.path.dirname(uproject)

    #
    # update uproject
    #

    uproject_dict = {}
    with open(uproject) as f:
        uproject_dict = json.load(f)

    save = False
    target_plugins_dir = os.path.realpath(os.path.join(os.path.dirname(__file__), "..", "cpp", "unreal_plugins")).replace("\\\\", "/").replace("\\", "/")

    if "AdditionalPluginDirectories" in uproject_dict:
        found = False
        for additional_plugins_dir in uproject_dict["AdditionalPluginDirectories"]:
            candidate_plugins_dir = additional_plugins_dir.replace("/", os.path.sep)
            if os.path.isabs(candidate_plugins_dir):
                candidate_plugins_dir = candidate_plugins_dir.replace("\\\\", "/").replace("\\", "/")
            else:
                candidate_plugins_dir = os.path.realpath(os.path.join(uproject_dir, candidate_plugins_dir)).replace("\\\\", "/").replace("\\", "/")
            if candidate_plugins_dir == target_plugins_dir:
                spear.log("AdditionalPluginDirectories already has a matching entry: ", additional_plugins_dir)
                found = True
                break
        if not found:
            spear.log("Adding to AdditionalPluginDirectories: ", target_plugins_dir)
            uproject_dict["AdditionalPluginDirectories"].append(target_plugins_dir)
            save = True
    else:
        spear.log("Creating AdditionalPluginDirectories and adding: ", target_plugins_dir)
        uproject_dict["AdditionalPluginDirectories"] = [target_plugins_dir]
        save = True

    if save:
        spear.log("Saving uproject: ", uproject)
        with open(uproject, "w") as f:
            json.dump(uproject_dict, f, indent=4, sort_keys=False)
            f.write("\n")

    #
    # update DefaultGame.ini
    #

    config_dir = os.path.realpath(os.path.join(external_project_dir, "Config"))
    default_game_ini_file = os.path.realpath(os.path.join(config_dir, "DefaultGame.ini"))
    default_game_bak_file = os.path.realpath(os.path.join(config_dir, "DefaultGame.ini.bak"))
    backup = False
    save = False
    sections = []

    if os.path.exists(default_game_ini_file):

        spear.log("Reading INI file: ", default_game_ini_file)
        with open(default_game_ini_file, "r") as f:
            lines = [ line for line in f ]

        current_section = {"heading": None, "lines": []}
        for line in lines:
            line_stripped = line.partition(";")[0].strip()
            if line_stripped.startswith("[") and line_stripped.endswith("]"):
                sections.append(current_section)
                current_section = {"heading": line_stripped.replace("[", "").replace("]", ""), "lines": [line]}
            else:
                current_section["lines"].append(line)
        sections.append(current_section)

        section_indices = np.nonzero([ section["heading"] == "/Script/UnrealEd.ProjectPackagingSettings" for section in sections ])[0]

        if len(section_indices) > 0:
            spear.log("Found /Script/UnrealEd.ProjectPackagingSettings section in existing INI file...")

            found_entry = False
            for section_index in section_indices:
                for line in sections[section_index]["lines"]:
                    line_stripped = line.partition(";")[0].strip()
                    if line_stripped == '+DirectoriesToAlwaysCook=(Path="/SpContent")':
                        spear.log('Found +DirectoriesToAlwaysCook=(Path="/SpContent") entry in existing section...')
                        found_entry = True
                        break
                if found_entry:
                    break

            if not found_entry:
                backup = True
                save = True
                section_index = section_indices[-1]
                section = sections[section_index]
                nonempty_line_indices = np.nonzero([ line.strip() != "" for line in section["lines"] ])[0]

                if len(nonempty_line_indices) > 0:
                    spear.log('Inserting +DirectoriesToAlwaysCook=(Path="/SpContent") entry in existing section...')
                    section["lines"].insert(nonempty_line_indices[-1] + 1, '+DirectoriesToAlwaysCook=(Path="/SpContent") ; auto-generated by spear/tools/install_plugins_in_external_project.py\n')
                else:
                    spear.log('Appending +DirectoriesToAlwaysCook=(Path="/SpContent") entry to existing section...')
                    section["lines"].append('+DirectoriesToAlwaysCook=(Path="/SpContent") ; auto-generated by spear/tools/install_plugins_in_external_project.py\n')

        else:
            backup = True
            save = True
            spear.log("Adding /Script/UnrealEd.ProjectPackagingSettings to INI file...")

            if len(sections) > 0 and len(sections[-1]["lines"]) > 0 and sections[-1]["lines"][-1].strip() == "":
                lines_prefix = []
            else:
                lines_prefix = ["\n"]

            section = {
                "heading": "/Script/UnrealEd.ProjectPackagingSettings",
                "lines": lines_prefix + ["[/Script/UnrealEd.ProjectPackagingSettings]\n", '+DirectoriesToAlwaysCook=(Path="/SpContent") ; auto-generated by spear/tools/install_plugins_in_external_project.py\n']}
            sections.append(section)

    else:
        backup = False
        save = True
        spear.log("Creating new INI file: ", default_game_ini_file)

        section = {
            "heading": "/Script/UnrealEd.ProjectPackagingSettings",
            "lines": ["[/Script/UnrealEd.ProjectPackagingSettings]\n", '+DirectoriesToAlwaysCook=(Path="/SpContent") ; auto-generated by spear/tools/install_plugins_in_external_project.py\n']}
        sections.append(section)

    if backup:
        spear.log("Creating backup INI file: ", default_game_bak_file)
        shutil.copy(default_game_ini_file, default_game_bak_file)

    if save:
        spear.log("Saving INI file...")
        os.makedirs(config_dir, exist_ok=True)
        with open(default_game_ini_file, "w") as f:
            for section in sections:
                for line in section["lines"]:
                    f.write(line)

    spear.log("Done.")
