#ifdef _MSC_VER
    #if PLATFORM_64BITS
        #undef INT
        #undef UINT
        #undef DWORD
        #undef FLOAT
        #undef TRUE
        #undef FALSE
        #undef InterlockedIncrement
        #undef InterlockedDecrement
        #undef InterlockedAdd
        #undef InterlockedExchange
        #undef InterlockedExchangeAdd
        #undef InterlockedCompareExchange
        #undef InterlockedAnd
        #undef InterlockedOr
        #undef InterlockedXor
        #undef InterlockedCompareExchangePointer
        #undef InterlockedExchange64
        #undef InterlockedExchangeAdd64
        #undef InterlockedCompareExchange64
        #undef InterlockedIncrement64
        #undef InterlockedDecrement64
    #else
        #undef INT
        #undef UINT
        #undef DWORD
        #undef FLOAT
        #undef TRUE
        #undef FALSE
        #undef InterlockedIncrement
        #undef InterlockedDecrement
        #undef InterlockedAdd
        #undef InterlockedExchange
        #undef InterlockedExchangeAdd
        #undef InterlockedCompareExchange
        #undef InterlockedAnd
        #undef InterlockedOr
        #undef InterlockedXor
        #undef InterlockedCompareExchangePointer
    #endif
#endif
